version: '3.2'
services:
  # Install cypress and cache the binary to a volume that is shared with all replicas
  # docker-compose --profile install up
  install:
    image: "cypress/browsers:node14.16.0-chrome90-ff88"
    command: npx cypress install
    working_dir: /e2e
    volumes:
      - cache:/root/.cache/Cypress
      - ../:/e2e
    profiles:
      - install
  # Open Cypress and attach to a X11 server
  # docker-compose --profile open up
  open:
    image: "cypress/browsers:node14.16.0-chrome90-ff88"
    environment:
      - CYPRESS_baseUrl=http://host.docker.internal:9001/
      - DISPLAY=host.docker.internal:0
    command: npx cypress open
    working_dir: /e2e
    volumes:
      - ../:/e2e
      - cache:/root/.cache/Cypress/
      - /tmp/.X11-unix:/tmp/.X11-unix
    profiles:
      - open
  # Run Cypress tests using the Cypress dashboard
  # CYPRESS_RECORD_KEY=FAKE-FAKE-FAKE-FAKE-FAKE BUILD_ID=$(uuidgen) docker-compose --profile run up
  run:
    deploy:
      replicas: 3
    image: "cypress/browsers:node14.16.0-chrome90-ff88"
    environment:
      - CYPRESS_baseUrl=http://host.docker.internal:9001/
      - CYPRESS_RECORD_KEY=${CYPRESS_RECORD_KEY}
    command: npx cypress run --record --parallel --browser chrome --ci-build-id ${BUILD_ID}
    working_dir: /e2e
    network_mode: host
    volumes:
      - ../:/e2e
      - cache:/root/.cache/Cypress/
    profiles:
      - run
volumes:
  cache: